---
- name: Ensure fail2ban is installed.
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Ensure fail2ban service is started and enabled.
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
