---
- name: Ensure essential SELinux packages are installed.
  become: true
  ansible.builtin.dnf:
    name:
      - policycoreutils
      - policycoreutils-python-utils
    state: present

- name: Enable custom port {{ ssh_port }}.
  become: true
  community.general.seport:
    ports: "{{ ssh_port }}"
    proto: tcp
    setype: ssh_port_t
    state: present

- name: Update ssh configuration.
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: 'sshd -t -f %s'
  loop:
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
    - regexp: "^Port"
      line: "Port {{ ssh_port }}"
  notify: Restart ssh.
