---
- name: Ensure there a exists a user {{ user_name }}.
  become: true
  ansible.builtin.user:
    name: "{{ user_name }}"
    state: present

- name: Add sudo rights for deployment user {{ user_name }}.
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ user_name }}
    create: true
    mode: "0644"
    owner: root
    group: root
    regexp: '^{{ user_name }}'
    line: '{{ user_name }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'
