---
- name: Ensure there exists a user named {{ server_security_ansible_user }}.
  ansible.builtin.user:
    name: "{{ server_security_ansible_user }}"
    state: present

- name: Add sudo rights for deployment user {{ server_security_ansible_user }}.
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ server_security_ansible_user }}
    create: true
    mode: "0640"
    owner: root
    group: root
    regexp: '^{{ server_security_ansible_user }}'
    line: '{{ server_security_ansible_user }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'
