---
- name: Set authorized key from file.
  ansible.posix.authorized_key:
    user: "{{ server_security_ansible_user }}"
    state: present
    key: "{{ server_security_public_key }}"

- name: Update ssh configuration.
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: 'sshd -t -f %s'
  loop:
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
    - regexp: "^Port"
      line: "Port {{ server_security_ssh_port }}"
  notify: Restart ssh.

- name: Flush handlers.
  ansible.builtin.meta: flush_handlers
