---
- name: Install unattended upgrades package.
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present

- name: Copy unattended-upgrades configuration files in place.
  ansible.builtin.template:
    src: "templates/debian/packages/{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - 20auto-upgrades
    - 50unattended-upgrades

- name: Run unattended-upgrades manually to verify configuration.
  ansible.builtin.command:
    cmd: "unattended-upgrades"
  register: result
  changed_when: "result.stdout != ''"
