---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance
    box: rockylinux/9
    cpus: 2
    memory: 1024
provisioner:
  name: ansible
verifier:
  name: ansible
